#!/bin/sh



INPUTPDF=$1
echo $INPUTPDF
PICTUREFILENAME=PICTURE.jpg
LABELFILENAME=LABEL.jpg
ADRESSFILENAME=ADRESS.jpg
FINALELABEL=FINAL.jpg
TEMPDIR=~/temp


echo $PICTUREFILENAME

#exit 0

convert -density 310 -trim $INPUTPDF  -quality 100 -flatten -sharpen 0x1.0 $TEMPDIR/$PICTUREFILENAME

convert $TEMPDIR/$PICTUREFILENAME -crop 850x960+1550+550 $TEMPDIR/$LABELFILENAME
convert $TEMPDIR/$PICTUREFILENAME -crop 750x960+173+550 $TEMPDIR/$ADRESSFILENAME
#convert $TEMPDIR/$PICTUREFILENAME -crop 213+750x1360+280 $TEMPDIR/$ADRESSFILENAME

convert $TEMPDIR/$LABELFILENAME $TEMPDIR/$ADRESSFILENAME -append $TEMPDIR/$FINALELABEL
